In [2]:
#GROUP BY 
import numpy as np
import pandas as pd

In [5]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}

df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [4]:
#df.groupby creates an object so it doesn't show on printing and the objects contain the original info divided into categories
cat=df.groupby('Category')
for i,j in cat:
    print(i)
    print(j)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [6]:
#group the data by category and calculate the sum for sales in each.
cat=df.groupby('Category')['Sales'].sum()
print(cat)

#group by store and calculate the sum of sales.
cat1=df.groupby('Store')['Sales'].sum()
print(cat1)

#group by multiple columns(category and store)
cat2=df.groupby(['Category','Store'])['Sales'].sum()
print(cat2)

Category
A    570
B    930
Name: Sales, dtype: int64
Store
S1    720
S2    780
Name: Sales, dtype: int64
Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [8]:
#AGGREGATION
print(df['Sales'].mean())
print(df['Sales'].median())
print(df['Sales'].mode()[0])
print(df['Sales'].min())
print(df['Sales'].max())
print(df['Sales'].count())
print(df['Sales'].std())
print()

#MULTIPLE FUNC IN A SINGLE LINE
print(df['Sales'].agg(['mean','median','max']))

187.5
190.0
200
100
300
8
66.06274074155351

mean      187.5
median    190.0
max       300.0
Name: Sales, dtype: float64

In [4]:
#PIVOT TABLE
data1 = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data1)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
print(df)

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    909     99   John  January      Q1
1  2023-01-02       B   West    322     62   Mary  January      Q1
2  2023-01-03       C  North    830     99    Bob  January      Q1
3  2023-01-04       D  South    806     26  Alice  January      Q1
4  2023-01-05       A   East    545     12   John  January      Q1
5  2023-01-06       B   West    563     69   Mary  January      Q1
6  2023-01-07       C  North    142     63    Bob  January      Q1
7  2023-01-08       D  South    663     56  Alice  January      Q1
8  2023-01-09       A   East    242     64   John  January      Q1
9  2023-01-10       B   West    264     33   Mary  January      Q1
10 2023-01-11       C  North    259     69    Bob  January      Q1
11 2023-01-12       D  South    494     72  Alice  January      Q1
12 2023-01-13       A   East    628     44   John  January      Q1
13 2023-01-14       B   West    103     12   Mary  January      Q1
14 2023-01-15       C  North    831     39    Bob  January      Q1
15 2023-01-16       D  South    113     36  Alice  January      Q1
16 2023-01-17       A   East    304     47   John  January      Q1
17 2023-01-18       B   West    662     33   Mary  January      Q1
18 2023-01-19       C  North    430     37    Bob  January      Q1
19 2023-01-20       D  South    680     64  Alice  January      Q1

In [6]:
#creates a modified table with separate desired values,columns and indexes.
print(pd.pivot_table(df,values='Sales',index='Region',columns='Product')) #by default the values fill up with mean which can be modified
print()
print(pd.pivot_table(df,values='Sales',index='Region',columns='Product',aggfunc='median'))

Product      A      B      C      D
Region
East     525.6    NaN    NaN    NaN
North      NaN    NaN  498.4    NaN
South      NaN    NaN    NaN  551.2
West       NaN  382.8    NaN    NaN

Product      A      B      C      D
Region
East     545.0    NaN    NaN    NaN
North      NaN    NaN  430.0    NaN
South      NaN    NaN    NaN  663.0
West       NaN  322.0    NaN    NaN

In [7]:
#crosstab:gives out the count
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0